baseURL = "https://littledrop.cz"
languageCode = "en-US"
title = "LittleDrop"
enableGitInfo = true
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
disableHugoGeneratorInject = true
enableEmoji = true
