name: "CS - EditorConfig"

on:
    workflow_call:

permissions:
    contents: read

jobs:
    editorconfig:
        name: ${{ inputs.name }}

        runs-on: "ubuntu-latest"

        env:
            GH_ACTOR: ${{ github.actor }}
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v5"

            -   name: "Restore editorconfig-checker cache"
                uses: "actions/cache@v5"
                with:
                    path: ".tools/var"
                    key: "editorconfig-checker-cache"
                    restore-keys: "editorconfig-checker-cache"

            -   name: "Run EditorConfig"
                run: "make editorconfig"
