name: "CS - Prettier"

on:
    workflow_call:

jobs:
    prettier:
        name: ${{ inputs.name }}

        runs-on: "ubuntu-latest"

        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v4"

            -   name: "Use Node.js"
                uses: "actions/setup-node@v6"
                with:
                    node-version: 25

            -   name: "Cache Node modules"
                uses: "actions/cache@v5"
                with:
                    path: |
                        ~/.npm
                        node_modules
                    key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
                    restore-keys: |
                        ${{ runner.os }}-node-

            -   name: "Install dependencies"
                run: "npm clean-install"

            -   name: "Run Prettier"
                run: "make prettier"
