name: "CS - Prettier"

on:
    workflow_call:

jobs:
    prettier:
        name: ${{ inputs.name }}

        runs-on: "ubuntu-latest"

        steps:
            -   name: "Checkout"
                uses: "actions/checkout@v4"

            -   name: "Run Prettier"
                run: "make prettier"
